### ISSUE TITLE
Выглядит так, что этот метод можно разбить, чтобы повысить читабельность

### ISSUE THREAD

**Issue by nuTak4istoDummyAcc** [Argin-hub/WebAppLibrary#10]
https://github.com/Argin-hub/WebAppLibrary/blob/f233c765ef056468d602733f8e0a8ad88f74a1d4/src/main/java/my/library/action/post/CreateAuthorAction.java#L21

**Comment by Argin-hub** [comment]
Не совсем представляю как его можно разбить?
В классе присутствует второй метод checkParamValid.

**Comment by nuTak4istoDummyAcc** [comment]
например, можно вынести подгрузку пропертей валидации в отдельный класс и тогда не придется загружать их при каждом запросе,

насчет checkParamValid, я заметил что код этого метода дублируется в CreateBookAction, RegisterAction и CreateAuthorAction, это тоже выглядит как кандидат на отдельный класс
