### ISSUE TITLE
В чем необходимость выноса в поле класса, а не сделать все внутри метода

### ISSUE THREAD

**Issue by nuTak4istoDummyAcc** [Argin-hub/WebAppLibrary#11]
https://github.com/Argin-hub/WebAppLibrary/blob/f233c765ef056468d602733f8e0a8ad88f74a1d4/src/main/java/my/library/action/post/CreateAuthorAction.java#L18

**Comment by Argin-hub** [comment]
Переменная используется внутри двух методов, поэтому не объявил внутри конкретного метода.

**Comment by nuTak4istoDummyAcc** [comment]
ок, пытался навести на мысль "а есть ли необходимость выносить в поле класса", 
вынос подобных флагов увеличивает связанность кода и любые правки могут повлечь изменение не только кода метода, но и полей класса

можно переписать метод валидации так, что поле не понадобится
