### ISSUE TITLE
Что будет если при комите упадет исключение?

### ISSUE THREAD

**Issue by nuTak4istoDummyAcc** [Argin-hub/WebAppLibrary#17]
https://github.com/Argin-hub/WebAppLibrary/blob/f233c765ef056468d602733f8e0a8ad88f74a1d4/src/main/java/my/library/dao/DaoFactory.java#L117
https://github.com/Argin-hub/WebAppLibrary/blob/f233c765ef056468d602733f8e0a8ad88f74a1d4/src/main/java/my/library/dao/DaoFactory.java#L118

**Comment by Argin-hub** [comment]
В данном методе используется try-catch для обработки исключений.
Рекомендуете добавить log в catch?
 
` public void commitTransaction() throws Exception {
        try {
            connection.commit();
            connection.setAutoCommit(true);
            log.info("Транзакция проведена");
        } catch (SQLException e) {
            throw new Exception("Cannot commit transaction", e);
        }
    }`

**Comment by nuTak4istoDummyAcc** [comment]
нет, нам ведь в любом случае нужно вернуть AutoCommit в исходное состояние, независимо от того, прошел комит или упал с исключением,

в текущей реализации при исключении в 117 строке, 118 не отработает
