### ISSUE TITLE
if,else,for ... в одну строку это конечно круто, до тех пор пока не начинаешь вносить изменения, рекомендую всегда добавлять скобки

### ISSUE THREAD

**Issue by nuTak4istoDummyAcc** [Argin-hub/WebAppLibrary#6]
https://github.com/Argin-hub/WebAppLibrary/blob/f233c765ef056468d602733f8e0a8ad88f74a1d4/src/main/java/my/library/action/get/PageBooksAction.java#L30

**Comment by Argin-hub** [comment]
Не совсем понял  "в одну строку"  и "добавлять скобки".
Имеется ввиду "try-with-resource" использовать?

**Comment by nuTak4istoDummyAcc** [comment]
нет, все гораздо проще, я рекомендую придерживаться одного стиля при написании if, else, for и дт. и избегать таких конструкций 
`if{
  ....
} else ...`

более удобно сразу писать
`if {
 ....
} else {
 .....
}`
тк при добавлении новой строки в else не нужно будет дописывать скобки, да читать код удобнее когда все оформлено одинаково
